### ISSUE TITLE
Odd error message when running the tutorial

### ISSUE THREAD

**Issue by bryanwb** [vonnagy/activator-service-container-tutorial#1]
I get the following message when I start the tutorial:

```
16:59:46.980 [run-main-0] INFO  c.g.v.s.c.ContainerBuilder$$anon$1 - The container service has been started
java.lang.ClassNotFoundException: xsbt.boot.Boot
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:190)
```

Otherwise the tutorial runs perfectly. I am using sbt version 0.13.7. Thoughts?

**Comment by vonnagy** [comment]
Bryan,

This error is caused when the system is trying to navigate the stack for the "main" method. It is triggered when trying to locate the entry point to the application. The source is located on line 68 in the [file](https://github.com/vonnagy/service-container/blob/master/service-container/src/main/scala/com/github/vonnagy/service/container/health/ContainerInfo.scala).

If a "main" function is located it tries to load the class and in this case the sbt jar file is not present. This occurs when running unit tests under sbt and in Activator. Here is the link to the sbt code: http://www.scala-sbt.org/0.13.5/sxr/xsbt/boot/Boot.scala.html. 

We can either not print the error or find a better way of locating the entry point. Either way, as you have found, it is simply log chatter and does not affect the process. Do you have any thoughts on this?
